[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_escrow_2023 = "3tWcxiouPwVkF8eiWWFPbxV8vayMVaR8BYMRFcz2zFK3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/beliv/wba/wba953abpL8wMfmX3WEZLd5UauUJJEYujxLar7roT5r.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
